import { Link } from 'react-router-dom'
import PaymentDisclosure from '@/components/PaymentDisclosure'

const terms = [
  ['Website access and license', 'The Sticker Smith provides this website for browsing print services, configuring products, uploading artwork, requesting quotes and managing orders. These terms include the end-user license for our website and its connected ordering features. We grant you a limited, non-exclusive, non-transferable permission to use those features for your own lawful personal or business purposes. The website software and shop branding remain the property of their respective owners. Do not copy or resell the software, interfere with the service, attempt unauthorized access, or use another person’s account without permission. We may restrict access used in violation of these terms; doing so does not remove obligations relating to an existing order.'],
  ['Your artwork and proofs', 'You retain your rights in artwork you submit. You must have permission to use it and authorize us to review, prepare proofs and produce your requested job. This permission does not by itself authorize portfolio publication. An on-screen preview is a placement guide, not an approved production proof. Check spelling, dimensions, layout, orientation and cut lines on the proof, then approve it or request changes. Production starts after the required payment, usable artwork and proof approval.'],
  ['Prices and order details', 'Review the product, finish, size, piece count, number of batches, add-ons, delivery choice and total before paying. One batch means one order of the displayed piece count. Custom quotes and any job-specific charges must be agreed before payment. The checkout or invoice shows the amount requested, including any listed discount, tax and delivery charges. Contact us before paying if the details do not match your request.'],
  ['Payments and connected services', 'Use the payment options displayed at checkout or on your approved invoice. The selected provider handles payment entry under its own terms and privacy notice. QuickBooks invoice payment services are provided by Intuit Payments Inc. Creating or viewing an invoice does not mean it has been paid. If you were charged without receiving confirmation, contact us with the payment reference. Authorized shop administrators may connect or disconnect QuickBooks; disconnecting does not delete existing accounting records or cancel orders.'],
  ['Production, delivery and pickup', 'Production estimates start after required payment, usable artwork and proof approval. Shipping transit is separate. A requested deadline is only confirmed when the shop agrees to it. Contact us about rush availability before ordering. For pickup, wait for a ready-for-pickup notice before visiting 23673 Connecticut St, Hayward, CA 94545.'],
  ['Changes, cancellations and print problems', 'Contact us promptly with your order reference for changes, cancellations, damaged deliveries or work that does not match the approved proof. Include photographs when helpful. The shop will review the work already performed and the issue, then explain available cancellation, refund or reprint options. No particular outcome is promised before that review. These terms do not limit rights or remedies provided by applicable law.'],
  ['Accounts, privacy and updates', 'Keep your account access secure and tell us about suspected misuse. Our Privacy Policy explains the information collected through this website. We will post changes to these terms with an updated effective date. Updating this page does not by itself change the agreed terms of an already accepted order.'],
]

const privacy = [
  ['Who this policy covers', 'The Sticker Smith operates tssprint.com. This policy describes information collected through the website and its order, quote, account and support features. For questions or privacy requests, contact thestickersmith@gmail.com, (510) 634-8203, or 23673 Connecticut St, Hayward, CA 94545.'],
  ['Information collected', 'You may provide your name, email, phone number, delivery address, account details, artwork, project instructions, product selections and messages. We also keep order, quote and payment-reference records. Website activity can include pages visited, product and cart interactions, checkout steps, referral and campaign information, browser/device details and visit identifiers. Hosting, analytics and payment providers may receive IP addresses and other technical information when you use their services.'],
  ['How information is used', 'We use information to respond to requests, prepare quotes and proofs, process and fulfill orders, restore saved carts, provide support, protect the service and keep business records. Website activity helps us understand which services people use and where the ordering flow fails. When you subscribe to our print list, your email is used for that subscription.'],
  ['Service providers and disclosures', 'Vercel hosts the website; Supabase supports accounts, database records and artwork storage; Resend supports email delivery. Google Analytics and Vercel Analytics measure website use. Payment information is handled by the provider shown at checkout or on the invoice, such as PayPal, Square or QuickBooks. QuickBooks invoice payment services are provided by Intuit Payments Inc. Order records include payment references, amounts and status. Do not submit full card numbers or security codes through artwork files or contact forms. Where an outside production or delivery provider helps fulfill a job, information needed for that work may be shared with that provider. Information may also be disclosed when required by law or needed to address fraud, security incidents or legal claims.'],
  ['QuickBooks connection', 'Where enabled, the shop’s QuickBooks integration sends customer and itemized order details to Intuit and reads invoice and payment records for accounting and reconciliation. The shop’s connection and accounting information are restricted to authorized administrators. Disconnecting stops future access through that connection; it does not erase records already held in QuickBooks or order records the shop must retain. Intuit’s services have their own privacy notice.'],
  ['Cookies, storage and online tracking', 'The website uses cookies or browser storage for sessions, carts, checkout details and attribution. Analytics and payment providers may use their own cookies and identifiers and may collect activity over time and across other websites under their own policies. You can restrict cookies in your browser, clear saved storage, or use Google’s Analytics opt-out tool. These controls can affect saved carts and sign-in. The website does not currently apply a separate response to browser Do Not Track or Global Privacy Control signals. Contact us to ask about your data choices.'],
  ['Your choices and requests', 'Email thestickersmith@gmail.com to request access to, correction of or deletion of information associated with your email or order, or to stop marketing emails. Include enough information to identify the relevant account or order; do not send passwords or card details. We may verify your identity before releasing or changing private information. Requests are handled subject to applicable law and records needed for outstanding jobs, accounting or disputes. You can ask to stop marketing messages while still receiving necessary order or account messages.'],
  ['Retention and security', 'There is no single automatic deletion deadline for all website records. Retention depends on the type of information, active orders and support needs, accounting requirements, security and disputes. Contact us about deletion of artwork or other records you no longer want retained. We use access restrictions and private production-file storage; QuickBooks connection tokens are encrypted on the server. No storage or transmission method guarantees complete security.'],
  ['Children and policy updates', 'Our ordering services are intended for adults and business customers. A parent or guardian can contact us about information a child has submitted. We will update the effective date when this policy changes and provide additional notice or obtain consent when required for material changes.'],
]

export default function Legal({ kind }: { kind: 'terms' | 'privacy' }) {
  const isTerms = kind === 'terms'
  return <article className="mx-auto w-full max-w-3xl px-6 py-12 md:py-16">
    <nav aria-label="Legal pages" className="mb-8 flex gap-6 text-sm">
      <Link to="/terms" aria-current={isTerms ? 'page' : undefined} className="text-primary underline underline-offset-4">Terms &amp; EULA</Link>
      <Link to="/privacy" aria-current={!isTerms ? 'page' : undefined} className="text-primary underline underline-offset-4">Privacy Policy</Link>
    </nav>
    <h1 className="text-3xl md:text-4xl font-black">{isTerms ? 'Website & ordering terms' : 'Privacy Policy'}</h1>
    <p className="mt-3 text-sm text-muted-foreground">Effective September 14, 2026 · The Sticker Smith</p>
    <p className="mt-6 text-muted-foreground leading-relaxed">{isTerms ? 'These terms cover use of our website and ordering features, including the end-user license agreement (EULA).' : 'How we use information when you browse, request a quote, upload artwork or order from us.'}</p>
    <div className="mt-9 space-y-8">
      {(isTerms ? terms : privacy).map(([title, text]) => <section key={title}><h2 className="text-xl font-bold">{title}</h2><p className="mt-2 leading-7 text-muted-foreground">{text}</p></section>)}
    </div>
    {!isTerms && <p className="mt-6 text-sm"><a href="https://policies.google.com/privacy" className="text-primary underline">Google privacy</a> · <a href="https://tools.google.com/dlpage/gaoptout" className="text-primary underline">Google Analytics opt-out</a> · <a href="https://www.intuit.com/privacy/" className="text-primary underline">Intuit privacy</a></p>}
    <aside className="mt-10 border-t border-border pt-6 space-y-3">
      <p className="font-bold">Questions? <a className="text-primary break-all underline" href="mailto:thestickersmith@gmail.com">thestickersmith@gmail.com</a></p>
      <Link to="/order-help" className="inline-block text-primary underline">Proofs, delivery &amp; order help</Link>
      <PaymentDisclosure />
    </aside>
  </article>
}
